admin:
  address:
    socket_address: { address: 0.0.0.0, port_value: 9901 }

static_resources:
  listeners:
    - name: base_case
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 10000
      filter_chains:
        - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                stat_prefix: ingress_http
                route_config:
                  name: local_route
                  virtual_hosts:
                    - name: backend
                      domains: ["*"]
                      routes:
                        - match:
                            prefix: "/"
                          route:
                            cluster: self
                          request_headers_to_add:
                            - header:
                                key: x-foo
                                value: "0 "
                              append_action: ADD_IF_ABSENT
                http_filters:
                  - name: envoy.filters.http.router
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router

    - name: recursive_case
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 10001
      filter_chains:
        - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                stat_prefix: ingress_http
                route_config:
                  name: local_route
                  virtual_hosts:
                    - name: local_fizzbuzz
                      domains: ["*"]
                      routes:
                        - match:
                            prefix: "/"
                            headers:
                              - name: x-foo
                                safe_regex_match:
                                  google_re2: {}
                                  regex: "^[1-9][0-9]{2,}$" # > 100
                          route:
                            cluster: self_output
                        - match:
                            prefix: "/"
                          route:
                            cluster: self
                http_filters:
                  - name: envoy.filters.http.lua
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua
                      default_source_code:
                        inline_string: |
                          function envoy_on_request(handle)
                            local headers = handle:headers()
                            local n = tonumber(headers:get("x-foo"))
                            if n == nil then
                              headers:add("x-foo-error", "parsing number failed")
                              return
                            end
                            headers:replace("x-foo", tostring(n + 1))
                          end
                  - name: envoy.filters.http.lua
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua
                      default_source_code:
                        inline_string: |
                          function envoy_on_request(handle)
                            local headers = handle:headers()
                            local n = headers:get("x-foo")
                            local output = headers:get("x-fizzbuzz") or ""
                            if output ~= "" then
                              output = output .. ","
                            end
                            local lookup = {"Fizz", "Buzz", "FizzBuzz"}
                            local fb = lookup[(n % 3 == 0 and 1 or 0) + (n % 5 == 0 and 2 or 0)] or n
                            headers:replace("x-fizzbuzz", output .. tostring(fb))
                          end
                  - name: envoy.filters.http.router
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
    - name: output
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 10002
      filter_chains:
        - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                stat_prefix: ingress_http
                route_config:
                  name: ignore_because_direct_reply
                  virtual_hosts:
                  - name: ignore_because_direct_reply
                    domains: ["*"]
                    routes:
                    - match:
                        prefix: "/"
                      route:
                        cluster: blackhole
                http_filters:
                  - name: envoy.filters.http.lua
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua
                      default_source_code:
                        inline_string: |
                          function envoy_on_request(handle)
                            local req_headers = handle:headers()
                            local resp_headers = {
                              [":status"] = "200",
                              ["content-type"] = "text/plain"
                            }

                            local fb = req_headers:get("x-fizzbuzz")
                            if fb == nil then
                              handle:respond(resp_headers, "FAIL, header x-fizzbuzz missing\n")
                            end

                            handle:respond(resp_headers, "FizzBuzz:\n" .. fb .. "\n")
                          end
                  - name: envoy.filters.http.router
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router

  clusters:
    - name: self
      type: STATIC
      load_assignment:
        cluster_name: self
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: 127.0.0.1
                      port_value: 10001
    - name: self_output
      type: STATIC
      load_assignment:
        cluster_name: self
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: 127.0.0.1
                      port_value: 10002
    - name: blackhole # Dummy (never reached)
      type: STATIC
      load_assignment:
        cluster_name: blackhole
        endpoints:
        - lb_endpoints:
          - endpoint:
              address:
                socket_address:
                  address: 127.0.0.1
                  port_value: 0
